### ISSUE TITLE
error: relation "snapshots" does not exist

### ISSUE THREAD

**Issue by git-manuel** [share/sharedb-postgres#21]
Hi,

I keep getting this error even after creating all the tables **snapshots** and **ops** from the script provided.

```
CREATE TABLE IF NOT EXISTS ops (
  collection character varying(255) not null,
  doc_id character varying(255) not null,
  version integer not null,
  operation jsonb not null, -- {v:0, create:{...}} or {v:n, op:[...]}
  PRIMARY KEY (collection, doc_id, version)
);

CREATE TABLE IF NOT EXISTS snapshots (
  collection character varying(255) not null,
  doc_id character varying(255) not null,
  doc_type character varying(255) not null,
  version integer not null,
  data jsonb not null,
  PRIMARY KEY (collection, doc_id)
);
```

```
error: relation "snapshots" does not exist
    at Parser.parseErrorMessage (/Users/../workspace/colaboration-demos/sharedb/examples/rich-text-presence/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/Users/../workspace/colaboration-demos/sharedb/examples/rich-text-presence/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/Users/../workspace/colaboration-demos/sharedb/examples/rich-text-presence/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/Users/../workspace/colaboration-demos/sharedb/examples/rich-text-presence/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
```

**Comment by git-manuel** [comment]
It seems sharedDB-postgres can't access no-public schema. I tried creating a table in a public scheme and it worked.  I wonder what
